name: Publish package to the Maven Central Repository and GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build packages
        run: gradle build
      - name: Grant permission to deploy.sh
        run: chmod 755 .github/workflows/commands/deploy.sh
      - name: Publish to the Maven Central Repository
        run: .github/workflows/commands/deploy.sh
        env: 
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
